//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04_Client_WinForm.Simplex {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://koa/")]
    [System.SerializableAttribute()]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sField;
        
        private int kField;
        
        private float fField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string s {
            get {
                return this.sField;
            }
            set {
                if ((object.ReferenceEquals(this.sField, value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int k {
            get {
                return this.kField;
            }
            set {
                if ((this.kField.Equals(value) != true)) {
                    this.kField = value;
                    this.RaisePropertyChanged("k");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float f {
            get {
                return this.fField;
            }
            set {
                if ((this.fField.Equals(value) != true)) {
                    this.fField = value;
                    this.RaisePropertyChanged("f");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://koa/", ConfigurationName="Simplex.SimplexSoap")]
    public interface SimplexSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Add-simplex) сообщения Add-simplex не соответствует значению по умолчанию (Add).
        [System.ServiceModel.OperationContractAttribute(Action="http://koa/Add-simplex", ReplyAction="*")]
        Lab04_Client_WinForm.Simplex.Addsimplex1 Add(Lab04_Client_WinForm.Simplex.Addsimplex request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://koa/Add-simplex", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab04_Client_WinForm.Simplex.Addsimplex1> AddAsync(Lab04_Client_WinForm.Simplex.Addsimplex request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Concat-simplex) сообщения Concat-simplex не соответствует значению по умолчанию (Concat).
        [System.ServiceModel.OperationContractAttribute(Action="http://koa/Concat-simplex", ReplyAction="*")]
        Lab04_Client_WinForm.Simplex.Concatsimplex1 Concat(Lab04_Client_WinForm.Simplex.Concatsimplex request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://koa/Concat-simplex", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab04_Client_WinForm.Simplex.Concatsimplex1> ConcatAsync(Lab04_Client_WinForm.Simplex.Concatsimplex request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Sum-simplex) сообщения Sum-simplex не соответствует значению по умолчанию (Sum).
        [System.ServiceModel.OperationContractAttribute(Action="http://koa/Sum-simplex", ReplyAction="*")]
        Lab04_Client_WinForm.Simplex.Sumsimplex1 Sum(Lab04_Client_WinForm.Simplex.Sumsimplex request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://koa/Sum-simplex", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab04_Client_WinForm.Simplex.Sumsimplex1> SumAsync(Lab04_Client_WinForm.Simplex.Sumsimplex request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Adds-simplex) сообщения Adds-simplex не соответствует значению по умолчанию (Adds).
        [System.ServiceModel.OperationContractAttribute(Action="http://koa/Adds-simplex", ReplyAction="*")]
        Lab04_Client_WinForm.Simplex.Addssimplex1 Adds(Lab04_Client_WinForm.Simplex.Addssimplex request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://koa/Adds-simplex", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab04_Client_WinForm.Simplex.Addssimplex1> AddsAsync(Lab04_Client_WinForm.Simplex.Addssimplex request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add-simplex", WrapperNamespace="http://koa/", IsWrapped=true)]
    public partial class Addsimplex {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://koa/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://koa/", Order=1)]
        public int y;
        
        public Addsimplex() {
        }
        
        public Addsimplex(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add-simplexResponse", WrapperNamespace="http://koa/", IsWrapped=true)]
    public partial class Addsimplex1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add-simplexResult", Namespace="http://koa/", Order=0)]
        public int AddsimplexResult;
        
        public Addsimplex1() {
        }
        
        public Addsimplex1(int AddsimplexResult) {
            this.AddsimplexResult = AddsimplexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Concat-simplex", WrapperNamespace="http://koa/", IsWrapped=true)]
    public partial class Concatsimplex {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://koa/", Order=0)]
        public string s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://koa/", Order=1)]
        public double d;
        
        public Concatsimplex() {
        }
        
        public Concatsimplex(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Concat-simplexResponse", WrapperNamespace="http://koa/", IsWrapped=true)]
    public partial class Concatsimplex1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Concat-simplexResult", Namespace="http://koa/", Order=0)]
        public string ConcatsimplexResult;
        
        public Concatsimplex1() {
        }
        
        public Concatsimplex1(string ConcatsimplexResult) {
            this.ConcatsimplexResult = ConcatsimplexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum-simplex", WrapperNamespace="http://koa/", IsWrapped=true)]
    public partial class Sumsimplex {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://koa/", Order=0)]
        public Lab04_Client_WinForm.Simplex.A a1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://koa/", Order=1)]
        public Lab04_Client_WinForm.Simplex.A a2;
        
        public Sumsimplex() {
        }
        
        public Sumsimplex(Lab04_Client_WinForm.Simplex.A a1, Lab04_Client_WinForm.Simplex.A a2) {
            this.a1 = a1;
            this.a2 = a2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum-simplexResponse", WrapperNamespace="http://koa/", IsWrapped=true)]
    public partial class Sumsimplex1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sum-simplexResult", Namespace="http://koa/", Order=0)]
        public Lab04_Client_WinForm.Simplex.A SumsimplexResult;
        
        public Sumsimplex1() {
        }
        
        public Sumsimplex1(Lab04_Client_WinForm.Simplex.A SumsimplexResult) {
            this.SumsimplexResult = SumsimplexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Adds-simplex", WrapperNamespace="http://koa/", IsWrapped=true)]
    public partial class Addssimplex {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://koa/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://koa/", Order=1)]
        public int y;
        
        public Addssimplex() {
        }
        
        public Addssimplex(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Adds-simplexResponse", WrapperNamespace="http://koa/", IsWrapped=true)]
    public partial class Addssimplex1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Adds-simplexResult", Namespace="http://koa/", Order=0)]
        public int AddssimplexResult;
        
        public Addssimplex1() {
        }
        
        public Addssimplex1(int AddssimplexResult) {
            this.AddssimplexResult = AddssimplexResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplexSoapChannel : Lab04_Client_WinForm.Simplex.SimplexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexSoapClient : System.ServiceModel.ClientBase<Lab04_Client_WinForm.Simplex.SimplexSoap>, Lab04_Client_WinForm.Simplex.SimplexSoap {
        
        public SimplexSoapClient() {
        }
        
        public SimplexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab04_Client_WinForm.Simplex.Addsimplex1 Lab04_Client_WinForm.Simplex.SimplexSoap.Add(Lab04_Client_WinForm.Simplex.Addsimplex request) {
            return base.Channel.Add(request);
        }
        
        public int Add(int x, int y) {
            Lab04_Client_WinForm.Simplex.Addsimplex inValue = new Lab04_Client_WinForm.Simplex.Addsimplex();
            inValue.x = x;
            inValue.y = y;
            Lab04_Client_WinForm.Simplex.Addsimplex1 retVal = ((Lab04_Client_WinForm.Simplex.SimplexSoap)(this)).Add(inValue);
            return retVal.AddsimplexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab04_Client_WinForm.Simplex.Addsimplex1> Lab04_Client_WinForm.Simplex.SimplexSoap.AddAsync(Lab04_Client_WinForm.Simplex.Addsimplex request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab04_Client_WinForm.Simplex.Addsimplex1> AddAsync(int x, int y) {
            Lab04_Client_WinForm.Simplex.Addsimplex inValue = new Lab04_Client_WinForm.Simplex.Addsimplex();
            inValue.x = x;
            inValue.y = y;
            return ((Lab04_Client_WinForm.Simplex.SimplexSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab04_Client_WinForm.Simplex.Concatsimplex1 Lab04_Client_WinForm.Simplex.SimplexSoap.Concat(Lab04_Client_WinForm.Simplex.Concatsimplex request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            Lab04_Client_WinForm.Simplex.Concatsimplex inValue = new Lab04_Client_WinForm.Simplex.Concatsimplex();
            inValue.s = s;
            inValue.d = d;
            Lab04_Client_WinForm.Simplex.Concatsimplex1 retVal = ((Lab04_Client_WinForm.Simplex.SimplexSoap)(this)).Concat(inValue);
            return retVal.ConcatsimplexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab04_Client_WinForm.Simplex.Concatsimplex1> Lab04_Client_WinForm.Simplex.SimplexSoap.ConcatAsync(Lab04_Client_WinForm.Simplex.Concatsimplex request) {
            return base.Channel.ConcatAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab04_Client_WinForm.Simplex.Concatsimplex1> ConcatAsync(string s, double d) {
            Lab04_Client_WinForm.Simplex.Concatsimplex inValue = new Lab04_Client_WinForm.Simplex.Concatsimplex();
            inValue.s = s;
            inValue.d = d;
            return ((Lab04_Client_WinForm.Simplex.SimplexSoap)(this)).ConcatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab04_Client_WinForm.Simplex.Sumsimplex1 Lab04_Client_WinForm.Simplex.SimplexSoap.Sum(Lab04_Client_WinForm.Simplex.Sumsimplex request) {
            return base.Channel.Sum(request);
        }
        
        public Lab04_Client_WinForm.Simplex.A Sum(Lab04_Client_WinForm.Simplex.A a1, Lab04_Client_WinForm.Simplex.A a2) {
            Lab04_Client_WinForm.Simplex.Sumsimplex inValue = new Lab04_Client_WinForm.Simplex.Sumsimplex();
            inValue.a1 = a1;
            inValue.a2 = a2;
            Lab04_Client_WinForm.Simplex.Sumsimplex1 retVal = ((Lab04_Client_WinForm.Simplex.SimplexSoap)(this)).Sum(inValue);
            return retVal.SumsimplexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab04_Client_WinForm.Simplex.Sumsimplex1> Lab04_Client_WinForm.Simplex.SimplexSoap.SumAsync(Lab04_Client_WinForm.Simplex.Sumsimplex request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab04_Client_WinForm.Simplex.Sumsimplex1> SumAsync(Lab04_Client_WinForm.Simplex.A a1, Lab04_Client_WinForm.Simplex.A a2) {
            Lab04_Client_WinForm.Simplex.Sumsimplex inValue = new Lab04_Client_WinForm.Simplex.Sumsimplex();
            inValue.a1 = a1;
            inValue.a2 = a2;
            return ((Lab04_Client_WinForm.Simplex.SimplexSoap)(this)).SumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab04_Client_WinForm.Simplex.Addssimplex1 Lab04_Client_WinForm.Simplex.SimplexSoap.Adds(Lab04_Client_WinForm.Simplex.Addssimplex request) {
            return base.Channel.Adds(request);
        }
        
        public int Adds(int x, int y) {
            Lab04_Client_WinForm.Simplex.Addssimplex inValue = new Lab04_Client_WinForm.Simplex.Addssimplex();
            inValue.x = x;
            inValue.y = y;
            Lab04_Client_WinForm.Simplex.Addssimplex1 retVal = ((Lab04_Client_WinForm.Simplex.SimplexSoap)(this)).Adds(inValue);
            return retVal.AddssimplexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab04_Client_WinForm.Simplex.Addssimplex1> Lab04_Client_WinForm.Simplex.SimplexSoap.AddsAsync(Lab04_Client_WinForm.Simplex.Addssimplex request) {
            return base.Channel.AddsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab04_Client_WinForm.Simplex.Addssimplex1> AddsAsync(int x, int y) {
            Lab04_Client_WinForm.Simplex.Addssimplex inValue = new Lab04_Client_WinForm.Simplex.Addssimplex();
            inValue.x = x;
            inValue.y = y;
            return ((Lab04_Client_WinForm.Simplex.SimplexSoap)(this)).AddsAsync(inValue);
        }
    }
}
