//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public long id { get; set; }
        public long studentId { get; set; }
        public string subj { get; set; }
        public int note { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
