//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 04.10.2022 18:35:16
namespace WebServices_Lab06Model
{
    
    /// <summary>
    /// There are no comments for WebServices_Lab06Entities in the schema.
    /// </summary>
    public partial class WebServices_Lab06Entities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new WebServices_Lab06Entities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public WebServices_Lab06Entities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Note> Notes
        {
            get
            {
                if ((this._Notes == null))
                {
                    this._Notes = base.CreateQuery<Note>("Notes");
                }
                return this._Notes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Note> _Notes;
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Student> Students
        {
            get
            {
                if ((this._Students == null))
                {
                    this._Students = base.CreateQuery<Student>("Students");
                }
                return this._Students;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Student> _Students;
        /// <summary>
        /// There are no comments for Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNotes(Note note)
        {
            base.AddObject("Notes", note);
        }
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"WebServices_Lab06Model\" xmlns=\"http://schemas.microsoft.com/ado/2009/" +
                "11/edm\"><EntityType Name=\"Note\"><Key><PropertyRef Name=\"id\" /></Key><Property Na" +
                "me=\"id\" Type=\"Edm.Int64\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xm" +
                "lns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Nam" +
                "e=\"studentId\" Type=\"Edm.Int64\" Nullable=\"false\" /><Property Name=\"subj\" Type=\"Ed" +
                "m.String\" Nullable=\"false\" MaxLength=\"256\" FixedLength=\"false\" Unicode=\"true\" />" +
                "<Property Name=\"note\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationProperty Na" +
                "me=\"Student\" Relationship=\"WebServices_Lab06Model.FK__Note__studentId__276EDEB3\"" +
                " ToRole=\"Student\" FromRole=\"Note\" /></EntityType><EntityType Name=\"Student\"><Key" +
                "><PropertyRef Name=\"id\" /></Key><Property Name=\"id\" Type=\"Edm.Int64\" Nullable=\"f" +
                "alse\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com" +
                "/ado/2009/02/edm/annotation\" /><Property Name=\"name\" Type=\"Edm.String\" Nullable=" +
                "\"false\" MaxLength=\"256\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty" +
                " Name=\"Note\" Relationship=\"WebServices_Lab06Model.FK__Note__studentId__276EDEB3\"" +
                " ToRole=\"Note\" FromRole=\"Student\" /></EntityType><Association Name=\"FK__Note__st" +
                "udentId__276EDEB3\"><End Type=\"WebServices_Lab06Model.Student\" Role=\"Student\" Mul" +
                "tiplicity=\"1\" /><End Type=\"WebServices_Lab06Model.Note\" Role=\"Note\" Multiplicity" +
                "=\"*\" /><ReferentialConstraint><Principal Role=\"Student\"><PropertyRef Name=\"id\" /" +
                "></Principal><Dependent Role=\"Note\"><PropertyRef Name=\"studentId\" /></Dependent>" +
                "</ReferentialConstraint></Association></Schema><Schema Namespace=\"Lab06.Models\" " +
                "xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"WebS" +
                "ervices_Lab06Entities\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Notes\"" +
                " EntityType=\"WebServices_Lab06Model.Note\" /><EntitySet Name=\"Students\" EntityTyp" +
                "e=\"WebServices_Lab06Model.Student\" /><FunctionImport Name=\"InsertStudent\" Return" +
                "Type=\"Edm.String\" m:HttpMethod=\"GET\"><Parameter Name=\"name\" Type=\"Edm.String\" />" +
                "</FunctionImport><FunctionImport Name=\"UpdateStudent\" ReturnType=\"Edm.String\" m:" +
                "HttpMethod=\"GET\"><Parameter Name=\"id\" Type=\"Edm.Int64\" Nullable=\"false\" /><Param" +
                "eter Name=\"name\" Type=\"Edm.String\" /></FunctionImport><FunctionImport Name=\"Dele" +
                "teStudent\" ReturnType=\"Edm.String\" m:HttpMethod=\"GET\"><Parameter Name=\"id\" Type=" +
                "\"Edm.Int64\" Nullable=\"false\" /></FunctionImport><FunctionImport Name=\"InsertNote" +
                "\" ReturnType=\"Edm.String\" m:HttpMethod=\"GET\"><Parameter Name=\"studentId\" Type=\"E" +
                "dm.Int64\" Nullable=\"false\" /><Parameter Name=\"subj\" Type=\"Edm.String\" /><Paramet" +
                "er Name=\"note\" Type=\"Edm.Int32\" Nullable=\"false\" /></FunctionImport><FunctionImp" +
                "ort Name=\"UpdateNote\" ReturnType=\"Edm.String\" m:HttpMethod=\"GET\"><Parameter Name" +
                "=\"id\" Type=\"Edm.Int64\" Nullable=\"false\" /><Parameter Name=\"studentId\" Type=\"Edm." +
                "Int64\" Nullable=\"false\" /><Parameter Name=\"subj\" Type=\"Edm.String\" /><Parameter " +
                "Name=\"note\" Type=\"Edm.Int32\" Nullable=\"false\" /></FunctionImport><FunctionImport" +
                " Name=\"DeleteNote\" ReturnType=\"Edm.String\" m:HttpMethod=\"GET\"><Parameter Name=\"i" +
                "d\" Type=\"Edm.Int64\" Nullable=\"false\" /></FunctionImport><AssociationSet Name=\"FK" +
                "__Note__studentId__276EDEB3\" Association=\"WebServices_Lab06Model.FK__Note__stude" +
                "ntId__276EDEB3\"><End Role=\"Note\" EntitySet=\"Notes\" /><End Role=\"Student\" EntityS" +
                "et=\"Students\" /></AssociationSet></EntityContainer></Schema></edmx:DataServices>" +
                "</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for WebServices_Lab06Model.Note in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Note
    {
        /// <summary>
        /// Create a new Note object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="studentId">Initial value of studentId.</param>
        /// <param name="subj">Initial value of subj.</param>
        /// <param name="note1">Initial value of note.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Note CreateNote(long ID, long studentId, string subj, int note1)
        {
            Note note = new Note();
            note.id = ID;
            note.studentId = studentId;
            note.subj = subj;
            note.note = note1;
            return note;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property studentId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long studentId
        {
            get
            {
                return this._studentId;
            }
            set
            {
                this.OnstudentIdChanging(value);
                this._studentId = value;
                this.OnstudentIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _studentId;
        partial void OnstudentIdChanging(long value);
        partial void OnstudentIdChanged();
        /// <summary>
        /// There are no comments for Property subj in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string subj
        {
            get
            {
                return this._subj;
            }
            set
            {
                this.OnsubjChanging(value);
                this._subj = value;
                this.OnsubjChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _subj;
        partial void OnsubjChanging(string value);
        partial void OnsubjChanged();
        /// <summary>
        /// There are no comments for Property note in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int note
        {
            get
            {
                return this._note;
            }
            set
            {
                this.OnnoteChanging(value);
                this._note = value;
                this.OnnoteChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _note;
        partial void OnnoteChanging(int value);
        partial void OnnoteChanged();
        /// <summary>
        /// There are no comments for Student in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Student Student
        {
            get
            {
                return this._Student;
            }
            set
            {
                this._Student = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Student _Student;
    }
    /// <summary>
    /// There are no comments for WebServices_Lab06Model.Student in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Student
    {
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="name">Initial value of name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Student CreateStudent(long ID, string name)
        {
            Student student = new Student();
            student.id = ID;
            student.name = name;
            return student;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Note in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Note> Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                if ((value != null))
                {
                    this._Note = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Note> _Note = new global::System.Collections.ObjectModel.Collection<Note>();
    }
}
